
SELECT BEBEDORES.ID, BEBEDORES.NOMBRE, COUNT(BEBEDORES.ID) AS NUM_APARICIONES
FROM BEBEDORES
INNER JOIN FRECUENTAN ON BEBEDORES.ID = FRECUENTAN.ID_BEBEDOR
INNER JOIN GUSTAN ON BEBEDORES.ID = GUSTAN.ID_BEBEDOR
GROUP BY BEBEDORES.NOMBRE, BEBEDORES.ID
ORDER BY NUM_APARICIONES DESC
FETCH FIRST 10 ROWS ONLY;

