SELECT BAR.NOMBRE, B.HORARIO, COUNT(DISTINCT(F.ID_BEBEDOR))
FROM 
(
    (SELECT CIUDAD, NOMBRE, ID FROM BARES)BAR
    FULL OUTER JOIN
    (SELECT ID_BAR, HORARIO, ID_BEBIDA FROM SIRVEN)B ON BAR.ID = B.ID_BAR
    FULL OUTER JOIN
    (SELECT ID_BEBIDA, ID_BEBEDOR FROM GUSTAN)C ON B.ID_BEBIDA = C.ID_BEBIDA
    FULL OUTER JOIN
    (SELECT ID, CIUDAD FROM BEBEDORES)D ON C.ID_BEBEDOR = D.ID
    FULL OUTER JOIN
    (SELECT ID, NOMBRE FROM BEBIDAS)E ON C.ID_BEBIDA = E.ID
    FULL OUTER JOIN
    (SELECT ID_BAR, ID_BEBEDOR, HORARIO FROM FRECUENTAN)F ON B.ID_BAR = F.ID_BAR
)
WHERE BAR.CIUDAD != D.CIUDAD AND E.NOMBRE = 'Duff'
GROUP BY BAR.NOMBRE, B.HORARIO
ORDER BY BAR.NOMBRE;
