SELECT A.NOMBRE, A.CIUDAD, COUNT(A.ID)
FROM
(
    (SELECT DISTINCT(ID), NOMBRE, PRESUPUESTO, CIUDAD FROM BARES WHERE PRESUPUESTO = 'Alto')A
    INNER JOIN
    (SELECT COUNT(ID_BEBIDA), ID_BEBIDA, ID_BAR FROM SIRVEN GROUP BY ID_BEBIDA, ID_BAR)B ON A.ID = B.ID_BAR
    INNER JOIN
    (SELECT ID, GRADO_ALCOHOL FROM BEBIDAS WHERE GRADO_ALCOHOL > 10)C ON B.ID_BEBIDA = C.ID
)
GROUP BY A.NOMBRE, A.CIUDAD;