SELECT A.CIUDAD, COUNT(ID_BAR) AS BARES
FROM  
(
    (SELECT CIUDAD, ID FROM BARES)A
    INNER JOIN
    (SELECT ID_BEBIDA, ID_BAR FROM SIRVEN)B ON A.ID = B.ID_BAR
    INNER JOIN
    (SELECT ID, TIPO, GRADO_ALCOHOL FROM BEBIDAS WHERE TIPO = '1' AND GRADO_ALCOHOL BETWEEN 8 AND 12)C ON B.ID_BEBIDA = C.ID
)

GROUP BY A.CIUDAD
ORDER BY BARES DESC
FETCH FIRST 1 ROWS ONLY;
